name: neo4j-export-fsharp

services:
  neo4j-export:
    build:
      context: .
      dockerfile: Dockerfile
    image: neo4j-export-fsharp:${VERSION:-latest}
    container_name: neo4j-export-fsharp
    
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    
    
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G 
        reservations:
          cpus: "0.5"
          memory: 512M

    env_file:
      - .env
    
    environment:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
      - DOTNET_NOLOGO=true

    volumes:
      - ./exports:/data/export

    network_mode: "host"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    restart: "no"
